version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout
      - setup_remote_docker
      - run: node --version
      - run:
          name: Unit tests
          command: docker run -e CI=true smakamura/docker-react npm run test 
      - run: node --version  