version: 2.1
  
orbs:
  docker: circleci/docker@1.6.0
  
jobs: 
  run_tests: 
    working_directory: ~/docker-react
    docker:
      - image: circleci/node:10.16.3
    steps: 
      - checkout
      - run: 
          name: docker build
          command: docker build -t smakamura/docker-react -f Dockerfile.dev .
      - run:
          name: unit_tests
          command: docker run smakamura/docker-react npm run test -- --coverage 
          
workflows:
  version: 2
  build_deploy:
    jobs:
      - run_tests
      
    
