version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container and verify it's working
          command: docker build -t smakamura/docker-react -f Dockerfile.dev .
      - run:
          name: Unit test
          command: docker run smakamura/docker-react npm run test -- --coverage    